apiVersion: apps/v1
kind: Deployment
metadata:
  name: argoapp
spec:
  selector:
    matchLabels:
      app: argoapp
  template:
    metadata:
      labels:
        app: argoapp
    spec:
      containers:
      - name: argoapp
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 80
